prompt = """
Di chuyển hoặc đổi tên tệp/thư mục trên thiết bị.
Nhập các tham số sau: <tên param source_path>, <tên param destination_path>.
Ví dụ thực thi: adb shell mv /sdcard/old.txt /sdcard/new.txt.
"""