description = "Thu hồi quyền của ứng dụng."
prompt = """
Thu hồi quyền của ứng dụng.
Nhập các tham số sau: <tên param package_name>, <tên param permission>.
Ví dụ thực thi: adb shell pm revoke <package_name> android.permission.READ_CONTACTS.
"""